// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9jroSrB-k9nBuyE0XoTQnfDzuhHhjHD0',
    appId: '1:858604490005:web:f51a795a9dd8ed997dad1c',
    messagingSenderId: '858604490005',
    projectId: 'finance-tracker-app-1163f',
    authDomain: 'finance-tracker-app-1163f.firebaseapp.com',
    storageBucket: 'finance-tracker-app-1163f.firebasestorage.app',
    measurementId: 'G-MCEWVJWDBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR25lYFQAMXlHm0HxepKLkWva5Z-6J6Ww',
    appId: '1:858604490005:android:27bb5f4877fdb3f47dad1c',
    messagingSenderId: '858604490005',
    projectId: 'finance-tracker-app-1163f',
    storageBucket: 'finance-tracker-app-1163f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9jroSrB-k9nBuyE0XoTQnfDzuhHhjHD0',
    appId: '1:858604490005:web:42c2d3f52365e3397dad1c',
    messagingSenderId: '858604490005',
    projectId: 'finance-tracker-app-1163f',
    authDomain: 'finance-tracker-app-1163f.firebaseapp.com',
    storageBucket: 'finance-tracker-app-1163f.firebasestorage.app',
    measurementId: 'G-ZD06XR2KT4',
  );
}
